# Generated by Django 5.2 on 2025-04-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordertracking",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="ordertracking",
            name="longitude",
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
